In [1]:
import numpy as np

In [2]:
x,y = np.mgrid[1:3:1,2:4:0.5]

In [3]:
x

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.]])

In [4]:
y

array([[2. , 2.5, 3. , 3.5],
       [2. , 2.5, 3. , 3.5]])

In [5]:
x1 = np.mgrid[2:4:1]
x1

array([2, 3])

In [6]:
x2 = np.mgrid[2:4:0.5]
x2

array([2. , 2.5, 3. , 3.5])

In [7]:
x3 = np.mgrid[1:3:1]
x3

array([1, 2])

In [8]:
y1 = np.mgrid[1:3:1,2:4:0.5]
y1

array([[[1. , 1. , 1. , 1. ],
        [2. , 2. , 2. , 2. ]],

       [[2. , 2.5, 3. , 3.5],
        [2. , 2.5, 3. , 3.5]]])

In [9]:
x.ravel()

array([1., 1., 1., 1., 2., 2., 2., 2.])

In [10]:
grid = np.c_[x.ravel(),y.ravel()]

In [11]:
grid

array([[1. , 2. ],
       [1. , 2.5],
       [1. , 3. ],
       [1. , 3.5],
       [2. , 2. ],
       [2. , 2.5],
       [2. , 3. ],
       [2. , 3.5]])