In [1]:
import tensorflow as tf
import numpy as np

In [2]:
seed = 23455

rdm = np.random.RandomState(seed=seed)
x = rdm.rand(32,2)
y_ = [[x1+x2+(rdm.rand()/10.0-0.05)] for (x1,x2) in x]
x = tf.cast(x,dtype=tf.float32)

w1 = tf.Variable(tf.random.normal([2,1],stddev=1,seed=1))

epoch = 15000
lr = 0.002

In [3]:
for epoch in range(epoch):
    with tf.GradientTape() as tape:
        y = tf.matmul(x,w1)
        loss_mes = tf.reduce_mean(tf.square(y_-y))
    grads = tape.gradient(loss_mes,w1)
    w1.assign_sub(lr*grads)
    
    if epoch % 500 ==0 :
        print("After %d training steps w1 is "% (epoch))
        print(w1.numpy(),"\n")
print("Final w1 is :", w1.numpy())

After 0 training steps w1 is 
[[-0.8096241]
 [ 1.4855157]] 

After 500 training steps w1 is 
[[-0.21934733]
 [ 1.6984866 ]] 

After 1000 training steps w1 is 
[[0.0893971]
 [1.673225 ]] 

After 1500 training steps w1 is 
[[0.28368822]
 [1.5853055 ]] 

After 2000 training steps w1 is 
[[0.423243 ]
 [1.4906037]] 

After 2500 training steps w1 is 
[[0.531055 ]
 [1.4053345]] 

After 3000 training steps w1 is 
[[0.61725086]
 [1.332841  ]] 

After 3500 training steps w1 is 
[[0.687201 ]
 [1.2725208]] 

After 4000 training steps w1 is 
[[0.7443262]
 [1.2227542]] 

After 4500 training steps w1 is 
[[0.7910986]
 [1.1818361]] 

After 5000 training steps w1 is 
[[0.82943517]
 [1.1482395 ]] 

After 5500 training steps w1 is 
[[0.860872 ]
 [1.1206709]] 

After 6000 training steps w1 is 
[[0.88665503]
 [1.098054  ]] 

After 6500 training steps w1 is 
[[0.90780276]
 [1.0795006 ]] 

After 7000 training steps w1 is 
[[0.92514884]
 [1.0642821 ]] 

After 7500 training steps w1 is 
[[0.93937725]
 [1.05179

In [5]:
cost = 1
profit = 99


for epoch in range(epoch):
    with tf.GradientTape() as tape:
        y = tf.matmul(x,w1)
        loss = tf.reduce_sum(tf.where(tf.greater(y,y_),(y-y_)*cost,(y_-y)*profit))
    grads = tape.gradient(loss,w1)
    w1.assign_sub(lr*grads)
    
    if epoch % 500 ==0 :
        print("After %d training steps w1 is "% (epoch))
        print(w1.numpy(),"\n")
print("Final w1 is :", w1.numpy())

After 0 training steps w1 is 
[[2.8579698]
 [2.8479836]] 

After 500 training steps w1 is 
[[1.1466794]
 [1.0426497]] 

After 1000 training steps w1 is 
[[1.1370593]
 [1.0739335]] 

After 1500 training steps w1 is 
[[1.1274396]
 [1.1052176]] 

After 2000 training steps w1 is 
[[1.1178197]
 [1.1365014]] 

After 2500 training steps w1 is 
[[1.1668332]
 [1.1790786]] 

After 3000 training steps w1 is 
[[1.1363947]
 [1.0338919]] 

After 3500 training steps w1 is 
[[1.1267751]
 [1.0651761]] 

After 4000 training steps w1 is 
[[1.1171551]
 [1.0964599]] 

After 4500 training steps w1 is 
[[1.1661687]
 [1.1390371]] 

After 5000 training steps w1 is 
[[1.1565483]
 [1.1703205]] 

After 5500 training steps w1 is 
[[1.1261101]
 [1.0251341]] 

After 6000 training steps w1 is 
[[1.1164902]
 [1.0564181]] 

After 6500 training steps w1 is 
[[1.1068704]
 [1.087702 ]] 

After 7000 training steps w1 is 
[[1.1558837]
 [1.130279 ]] 

After 7500 training steps w1 is 
[[1.146264]
 [1.161563]] 

After 8000 tra